modLoader="javafml" #mandatory
loaderVersion="[47,)" # Ensure this matches your Forge version range
license="MIT" # Replace with your mod's license, such as "All Rights Reserved" or an open-source license

[[mods]]
modId="jmresurrected" # This must match the MODID in your Java class
version="1.7.0" # Replace with your mod's version
displayName="John Mod Resurrected" # Name of your mod
authors="Your Name" # Replace with your name or team name
description='''
A mod that adds custom items and gameplay features.
''' # Write a brief description of your mod

[[dependencies.jmresurrected]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.jmresurrected]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"

# Features are specific properties of the game environment, that you may want to declare you require. This example declares
# that your mod requires GL version 3.2 or higher. Other features will be added. They are side aware so declaring this won't
# stop your mod loading on the server for example.
#[features.${mod_id}]
#openGLVersion="[3.2,)"